version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - appnetwork
    depends_on:
      - mysql
  mysql:
    image: "mysql"

    environment:
      MYSQL_ROOT_PASSWORD: tjdetwill
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnetwork

networks:
  appnetwork: