version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    networks:
       appnetwork:
            aliases:
            - flask-app
    

    depends_on:
      - mysql
  mysql:
    image: "mysql"

    environment:
      MYSQL_ROOT_PASSWORD: tjdetwill
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnetwork
  
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
        - app
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
        - appnetwork
    ports:
        - 80:80

networks:
  appnetwork: