version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    networks:
       appnetwork:
            aliases:
            - flask-app
    

    depends_on:
      - mysql
  mysql:
    image: "mysql"

    environment:
      MYSQL_ROOT_PASSWORD: tjdetwill
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnetwork
  
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
        - app
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
        - appnetwork
    ports:
        - 80:80

  new_relic_agent:
    container_name: newrelic-infra
    build:
      context: .
      dockerfile: newrelic-infra.dockerfile
    cap_add:
      - SYS_PTRACE
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
    networks:
      - appnetwork

networks:
  appnetwork: